Nehan.OutlineContext = (function(){
  /**
     @memberof Nehan
     @class OutlineContext
     @classdesc outline context object. outline is generated by section root element, sectionning element, heading element etc.
     @constructor
     @param markup_name {String} - section root name like "body", "fieldset", "blockquote" etc.
  */
  function OutlineContext(markup_name){
    this.logs = [];
    this.markupName = markup_name;
  }

  OutlineContext.prototype = {
    /**
       @memberof Nehan.OutlineContext
       @return {boolean}
    */
    isEmpty : function(){
      return this.logs.length === 0;
    },
    /**
       @memberof Nehan.OutlineContext
       @return {Object} log object
    */
    get : function(index){
      return this.logs[index] || null;
    },
    /**
       @memberof Nehan.OutlineContext
       @return {String}
    */
    getMarkupName : function(){
      return this.markupName;
    },
    /**
       @memberof Nehan.OutlineContext
       @param opt {Object}
       @param opt.type {String} - markup name
       @param opt.pageNo {int} - page no of section
       @return {Nehan.OutlineContext}
    */
    startSection : function(opt){
      this.logs.push({
	name:"start-section",
	type:opt.type,
	pageNo:opt.pageNo
      });
      return this;
    },
    /**
       @memberof Nehan.OutlineContext
       @param type {String} - markup name
       @return {Nehan.OutlineContext}
    */
    endSection : function(type){
      this.logs.push({
	name:"end-section",
	type:type
      });
      return this;
    },
    /**
       @memberof Nehan.OutlineContext
       @param opt {Object}
       @param opt.type {String} - markup name
       @param opt.headerId {String} - unique header id(associate header box object with outline)
       @pramm opt.pageNo {int} - page no of this header
       @param opt.rank {int} - header rank(1 - 6)
       @param opt.title {String} - header title
       @return {String} header id
    */
    addHeader : function(opt){
      this.logs.push({
	name:"set-header",
	headerId:opt.headerId,
	pageNo:opt.pageNo,
	type:opt.type,
	rank:opt.rank,
	title:opt.title
      });
      return opt.headerId;
    }
  };

  return OutlineContext;
})();
