var OutlineContext = (function(){
  /**
     @memberof Nehan
     @class OutlineContext
     @classdesc outline context object. outline is generated by section root element, sectionning element, heading element etc.
     @constructor
     @param markup_name {String} - section root name like "body", "fieldset", "blockquote" etc.
  */
  function OutlineContext(markup_name){
    this.logs = [];
    this.markupName = markup_name;
  }

  OutlineContext.prototype = {
    /**
       @memberof Nehan.OutlineContext
       @return {boolean}
    */
    isEmpty : function(){
      return this.logs.length === 0;
    },
    /**
       @memberof Nehan.OutlineContext
       @return {Object} - log object
    */
    get : function(index){
      return this.logs[index] || null;
    },
    /**
       @memberof Nehan.OutlineContext
       @return {String}
    */
    getMarkupName : function(){
      return this.markupName;
    },
    /**
       @memberof Nehan.OutlineContext
       @param type {String} - markup name
       @return {Nehan.OutlineContext}
    */
    startSection : function(type){
      this.logs.push({
	name:"start-section",
	type:type,
	pageNo:DocumentContext.getPageNo()
      });
      return this;
    },
    /**
       @memberof Nehan.OutlineContext
       @param type {String} - markup name
       @return {Nehan.OutlineContext}
    */
    endSection : function(type){
      this.logs.push({
	name:"end-section",
	type:type
      });
      return this;
    },
    /**
       @memberof Nehan.OutlineContext
       @param opt {Object}
       @param opt.type {String} - markup name
       @param opt.rank {int} - header rank(1 - 6)
       @param opt.title {String} - header title
       @return {String} - header id
    */
    addHeader : function(opt){
      // header id is used to associate header box object with outline.
      var header_id = DocumentContext.genHeaderId();
      this.logs.push({
	name:"set-header",
	type:opt.type,
	rank:opt.rank,
	title:opt.title,
	pageNo:DocumentContext.getPageNo(),
	headerId:header_id
      });
      return header_id;
    }
  };

  return OutlineContext;
})();
