Nehan.OutlineContext = (function(){
  /**
     @memberof Nehan
     @class OutlineContext
     @classdesc outline context object. outline is generated by section root element, sectionning element, heading element etc.
     @constructor
     @param markup_name {String} - section root name like "body", "fieldset", "blockquote" etc.
  */
  function OutlineContext(markup_name){
    this.logs = [];
    this.markupName = markup_name || "body";
  }

  /**
   @memberof Nehan.OutlineContext
   @return {boolean}
   */
  OutlineContext.prototype.isEmpty = function(){
    return this.logs.length === 0;
  };

  /**
   @memberof Nehan.OutlineContext
   @return {Object} log object
   */
  OutlineContext.prototype.get = function(index){
    return this.logs[index] || null;
  };

  /**
   @memberof Nehan.OutlineContext
   @return {String}
   */
  OutlineContext.prototype.getMarkupName = function(){
    return this.markupName;
  };

  /**
   @memberof Nehan.OutlineContext
   @param value {Object}
   @return {Nehan.OutlineContext}
   */
  OutlineContext.prototype.add = function(value){
    this.logs.push(value);
    return this;
  };

  return OutlineContext;
})();
